'\" t
.\"     Title: hgignore
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 07/23/2009
.\"    Manual: Mercurial Manual
.\"    Source: Mercurial
.\"  Language: English
.\"
.TH "HGIGNORE" "5" "07/23/2009" "Mercurial" "Mercurial Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
hgignore \- syntax for Mercurial ignore files
.SH "SYNOPSIS"
.sp
The Mercurial system uses a file called \&.hgignore in the root directory of a repository to control its behavior when it searches for files that it is not currently tracking\&.
.SH "DESCRIPTION"
.sp
The working directory of a Mercurial repository will often contain files that should not be tracked by Mercurial\&. These include backup files created by editors and build products created by compilers\&. These files can be ignored by listing them in a \&.hgignore file in the root of the working directory\&. The \&.hgignore file must be created manually\&. It is typically put under version control, so that the settings will propagate to other repositories with push and pull\&.
.sp
An untracked file is ignored if its path relative to the repository root directory, or any prefix path of that path, is matched against any pattern in \&.hgignore\&.
.sp
For example, say we have an an untracked file, file\&.c, at a/b/file\&.c inside our repository\&. Mercurial will ignore file\&.c if any pattern in \&.hgignore matches a/b/file\&.c, a/b or a\&.
.sp
In addition, a Mercurial configuration file can reference a set of per\-user or global ignore files\&. See the hgrc(5) man page for details of how to configure these files\&. Look for the "ignore" entry in the "ui" section\&.
.sp
To control Mercurial\(cqs handling of files that it manages, see the hg(1) man page\&. Look for the "\-I" and "\-X" options\&.
.SH "SYNTAX"
.sp
An ignore file is a plain text file consisting of a list of patterns, with one pattern per line\&. Empty lines are skipped\&. The "#" character is treated as a comment character, and the "\e" character is treated as an escape character\&.
.sp
Mercurial supports several pattern syntaxes\&. The default syntax used is Python/Perl\-style regular expressions\&.
.sp
To change the syntax used, use a line of the following form:
.sp
syntax: NAME
.sp
where NAME is one of the following:
.PP
regexp
.RS 4
Regular expression, Python/Perl syntax\&.
.RE
.PP
glob
.RS 4
Shell\-style glob\&.
.RE
.sp
The chosen syntax stays in effect when parsing all patterns that follow, until another syntax is selected\&.
.sp
Neither glob nor regexp patterns are rooted\&. A glob\-syntax pattern of the form "*\&.c" will match a file ending in "\&.c" in any directory, and a regexp pattern of the form "\e\&.c$" will do the same\&. To root a regexp pattern, start it with "^"\&.
.SH "EXAMPLE"
.sp
Here is an example ignore file\&.
.sp
.if n \{\
.RS 4
.\}
.nf
# use glob syntax\&.
syntax: glob
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
*\&.elc
*\&.pyc
*~
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
# switch to regexp syntax\&.
syntax: regexp
^\e\&.pc/
.fi
.if n \{\
.RE
.\}
.SH "AUTHOR"
.sp
Vadim Gelfer <\m[blue]\fBvadim\&.gelfer@gmail\&.com\fR\m[]\&\s-2\u[1]\d\s+2>
.sp
Mercurial was written by Matt Mackall <\m[blue]\fBmpm@selenic\&.com\fR\m[]\&\s-2\u[2]\d\s+2>\&.
.SH "SEE ALSO"
.sp
hg(1), hgrc(5)
.SH "COPYING"
.sp
This manual page is copyright 2006 Vadim Gelfer\&. Mercurial is copyright 2005\-2009 Matt Mackall\&. Free use of this software is granted under the terms of the GNU General Public License (GPL)\&.
.SH "NOTES"
.IP " 1." 4
vadim.gelfer@gmail.com
.RS 4
\%mailto:vadim.gelfer@gmail.com
.RE
.IP " 2." 4
mpm@selenic.com
.RS 4
\%mailto:mpm@selenic.com
.RE
